import type {
  HospitalMetrics,
  ForecastPoint,
  RiskFactor,
  EarlyWarningAlert,
  OperationalBottleneck,
  Recommendation,
  WhatIfParameters,
  WhatIfSimulationResult,
} from '../types/index.ts';
import { mlPredictionService } from '../ml/mlPredictionService';
import type { PredictionOutput, DatasetSummary } from '../ml/types';

export interface IPredictionService {
  generateForecast(current: HospitalMetrics, surgeActive: boolean): ForecastPoint[];
  getRiskFactors(current: HospitalMetrics, surgeActive: boolean): RiskFactor[];
  getEarlyWarning(current: HospitalMetrics, surgeActive: boolean): EarlyWarningAlert;
  getBottleneck(current: HospitalMetrics, surgeActive: boolean): OperationalBottleneck;
  getRecommendations(current: HospitalMetrics, surgeActive: boolean): Recommendation[];
  simulateWhatIf(baseline: HospitalMetrics, params: WhatIfParameters): WhatIfSimulationResult;
  getMLPrediction(current: HospitalMetrics): PredictionOutput;
  getMLSummary(): DatasetSummary;
}

class DeterministicPredictionEngine implements IPredictionService {
  getMLPrediction(current: HospitalMetrics): PredictionOutput {
    return mlPredictionService.predictCongestion({
      patientsArrived: current.patientsArrived,
      ambulanceArrivals: current.ambulanceArrivals,
      patientsWaiting: current.patientsWaiting,
      bedsAvailable: current.bedsAvailable,
      bedsOccupied: current.bedsOccupied,
      bedsTotal: current.bedsTotal,
      doctorsAvailable: current.staffDoctors,
      nursesAvailable: current.staffNurses,
      supportStaffAvailable: current.staffSupport,
      averageWaitTime: current.averageWaitTime,
      averageTreatmentTime: current.averageTreatmentTime,
      admissions: current.admissions,
      discharges: current.discharges,
      recentArrivalTrend: current.arrivalBaseline > 0 ? current.patientsArrived / current.arrivalBaseline : 1.0,
      recentCongestionTrend: current.prevHourCongestionRisk > 0 ? current.congestionRisk / current.prevHourCongestionRisk : 1.0,
    });
  }

  getMLSummary(): DatasetSummary {
    return mlPredictionService.getDatasetSummary();
  }

  generateForecast(current: HospitalMetrics, surgeActive: boolean): ForecastPoint[] {
    const now = new Date();
    const points: ForecastPoint[] = [];

    // Run the Machine Learning Random Forest Model
    const mlPrediction = this.getMLPrediction(current);

    // Past 2 hours: -120m, -90m, -60m, -30m
    const pastOffsets = [-120, -90, -60, -30];
    pastOffsets.forEach((mins) => {
      const pointTime = new Date(now.getTime() + mins * 60 * 1000);
      const hours = pointTime.getHours().toString().padStart(2, '0');
      const minutes = pointTime.getMinutes().toString().padStart(2, '0');
      
      // Historical curve leading up to current observation
      let risk = 64;
      if (mins === -90) risk = 68;
      if (mins === -60) risk = 72;
      if (mins === -30) risk = 77;
      if (surgeActive) risk = Math.min(88, risk + 8);

      points.push({
        timestamp: pointTime.toISOString(),
        timeLabel: `${hours}:${minutes} (${mins}m)`,
        isHistorical: true,
        congestionRisk: risk,
        predictedWaitTime: Math.round(30 + (risk / 100) * 20),
        predictedBedDemand: Math.round(55 + (risk / 100) * 10),
        confidence: 98,
        upperBound: risk + 2,
        lowerBound: risk - 2,
      });
    });

    // Current point: Now
    const nowHours = now.getHours().toString().padStart(2, '0');
    const nowMinutes = now.getMinutes().toString().padStart(2, '0');
    const nowRisk = surgeActive ? 94 : current.congestionRisk;

    points.push({
      timestamp: now.toISOString(),
      timeLabel: `Now (${nowHours}:${nowMinutes})`,
      isHistorical: false,
      congestionRisk: nowRisk,
      predictedWaitTime: surgeActive ? 76 : current.averageWaitTime,
      predictedBedDemand: surgeActive ? 68 : current.bedsOccupied,
      confidence: Math.round(mlPrediction.confidence * 100),
      upperBound: nowRisk + 2,
      lowerBound: nowRisk - 2,
    });

    // Future points: +30m, +60m, +90m, +120m generated by the trained ML Random Forest Regressors
    const futureOffsets = [
      { mins: 30, key: '30' as const, waitDelta: 12, bedDemand: 65 },
      { mins: 60, key: '60' as const, waitDelta: 24, bedDemand: 68 },
      { mins: 90, key: '90' as const, waitDelta: 31, bedDemand: 69 },
      { mins: 120, key: '120' as const, waitDelta: 19, bedDemand: 67 },
    ];

    futureOffsets.forEach((item) => {
      const pointTime = new Date(now.getTime() + item.mins * 60 * 1000);
      const hours = pointTime.getHours().toString().padStart(2, '0');
      const minutes = pointTime.getMinutes().toString().padStart(2, '0');

      // Base target risk from ML Random Forest regression output
      const mlRisk = mlPrediction.forecastPercentages[item.key];
      const targetRisk = surgeActive ? Math.min(99, Math.max(mlRisk + 6, 92)) : mlRisk;
      const baseWait = surgeActive ? 70 : current.averageWaitTime;

      const modelConfidence = Math.max(75, Math.round(mlPrediction.confidence * 100 - (item.mins * 0.1)));

      points.push({
        timestamp: pointTime.toISOString(),
        timeLabel: `+${item.mins}m (${hours}:${minutes})`,
        isHistorical: false,
        congestionRisk: targetRisk,
        predictedWaitTime: baseWait + item.waitDelta,
        predictedBedDemand: item.bedDemand + (surgeActive ? 3 : 0),
        confidence: modelConfidence,
        upperBound: Math.min(100, targetRisk + Math.round(item.mins * 0.05 + 3)),
        lowerBound: Math.max(50, targetRisk - Math.round(item.mins * 0.06 + 3)),
      });
    });

    return points;
  }

  getRiskFactors(current: HospitalMetrics, surgeActive: boolean): RiskFactor[] {
    if (surgeActive) {
      return [
        {
          id: 'rf-arrivals',
          name: 'Patient Arrivals Surge',
          changeValue: '+60%',
          changeType: 'increase',
          isSevere: true,
          description: 'Sudden high-acuity influx from regional casualty incident and EMS transfers.',
        },
        {
          id: 'rf-beds',
          name: 'Available Bed Exhaustion',
          changeValue: '-30%',
          changeType: 'decrease',
          isSevere: true,
          description: 'Critical care and acute care bay reserves depleted below safe operating buffer.',
        },
        {
          id: 'rf-wait',
          name: 'Triage Queue Expansion',
          changeValue: '+45%',
          changeType: 'increase',
          isSevere: true,
          description: 'Waiting room capacity breached; boarding times escalating across categories 3-5.',
        },
        {
          id: 'rf-staff',
          name: 'Staff Saturation',
          changeValue: '-18%',
          changeType: 'decrease',
          isSevere: true,
          description: 'Acute zone nursing ratios exceeded safety threshold of 1:4 per provider.',
        },
      ];
    }

    const occupancyRate = Math.round((current.bedsOccupied / (current.bedsTotal || 70)) * 100);
    const waitDelta = current.averageWaitTime - (current.prevHourWaitTime || 60);

    return [
      {
        id: 'rf-arrivals',
        name: 'Patient Inflow Rate',
        changeValue: `${current.patientsArrived} pts`,
        changeType: current.patientsArrived > 6 ? 'increase' : 'decrease',
        isSevere: current.patientsArrived > 10,
        description: current.patientsArrived <= 3
          ? `Arrival velocity is quiet (${current.patientsArrived} patient in current 15-min interval).`
          : `Current intake pace is ${current.patientsArrived} arrivals in this interval.`,
      },
      {
        id: 'rf-beds',
        name: 'Inpatient Bed Buffer',
        changeValue: `${current.bedsAvailable} avail`,
        changeType: current.bedsAvailable <= 15 ? 'decrease' : 'increase',
        isSevere: current.bedsAvailable <= 12,
        description: `${current.bedsOccupied}/${current.bedsTotal} beds currently occupied (${occupancyRate}% utilization).`,
      },
      {
        id: 'rf-wait',
        name: 'Average Wait Time',
        changeValue: `${current.averageWaitTime} min`,
        changeType: waitDelta > 0 ? 'increase' : 'decrease',
        isSevere: current.averageWaitTime > 75,
        description: `Average door-to-provider wait time is ${current.averageWaitTime} min across triage categories.`,
      },
      {
        id: 'rf-staff',
        name: 'Clinical Staffing',
        changeValue: `${current.staffNurses} RNs`,
        changeType: current.staffNurses >= 12 ? 'increase' : 'decrease',
        isSevere: current.staffNurses < 10,
        description: `${current.staffDoctors} physicians and ${current.staffNurses} nurses on active floor roster.`,
      },
    ];
  }

  getEarlyWarning(current: HospitalMetrics, surgeActive: boolean): EarlyWarningAlert {
    if (surgeActive) {
      return {
        id: 'ew-surge-critical',
        severity: 'CRITICAL',
        title: 'CRITICAL SURGE PROTOCOL ACTIVATED',
        projectedPeak: '98% in 45 minutes',
        primaryPressure: 'Mass Casualty Inflow + Complete Bed Saturation',
        preparationWindow: '10–15 minutes (URGENT)',
        timestamp: new Date().toISOString(),
      };
    }

    return {
      id: 'ew-high-congestion',
      severity: current.congestionRisk >= 80 ? 'HIGH' : 'ELEVATED',
      title: 'HIGH CONGESTION EXPECTED',
      projectedPeak: '94% in 75 minutes',
      primaryPressure: 'Patient arrivals + Bed availability',
      preparationWindow: '20–30 minutes',
      timestamp: new Date().toISOString(),
    };
  }

  getBottleneck(current: HospitalMetrics, surgeActive: boolean): OperationalBottleneck {
    if (surgeActive) {
      return {
        name: 'ACUTE BED CAPACITY & EMS OFFLOAD',
        category: 'BEDS',
        description: 'Bed occupancy is at 97% with 3 pending ambulance offloads. Emergency department dwell time is compounding, threatening ambulance turn-around compliance.',
        impactLevel: 'CRITICAL',
        confidence: 94,
        secondaryFactor: 'Triage Assessment Throughput',
        projectedResolutionTime: '45 mins with surge activation',
      };
    }

    return {
      name: 'BED AVAILABILITY',
      category: 'BEDS',
      description: 'Bed occupancy is approaching operational capacity while arrivals are increasing. Without intervention, waiting time is projected to increase over the next hour.',
      impactLevel: 'HIGH',
      confidence: 89,
      secondaryFactor: 'Inpatient Ward Bed Request Backlog',
      projectedResolutionTime: '30 mins with intervention',
    };
  }

  getRecommendations(_current: HospitalMetrics, surgeActive: boolean): Recommendation[] {
    if (surgeActive) {
      return [
        {
          id: 'rec-surge-1',
          priority: 'CRITICAL',
          title: 'ACTIVATE 8 SURGE OVERFLOW BAYS',
          reason: 'Emergency department acute bay capacity at 97%; incoming EMS priority 1 transfers require unassigned monitors.',
          expectedImpact: 'Reduce projected peak congestion by ~16%',
          actionType: 'OPEN_BEDS',
          impactPercentage: 16,
          status: 'PENDING',
        },
        {
          id: 'rec-surge-2',
          priority: 'CRITICAL',
          title: 'CALL IN RAPID-RESPONSE NURSE POOL (+4 NURSES)',
          reason: 'Direct nurse-to-patient ratio currently breached in Acute Pod B and Trauma Resus.',
          expectedImpact: 'Restore safe nurse ratio and lower wait times by ~22 min',
          actionType: 'REALLOCATE_NURSES',
          impactPercentage: 14,
          status: 'PENDING',
        },
        {
          id: 'rec-surge-3',
          priority: 'HIGH',
          title: 'INITIATE REGIONAL EMS DIVERSION ADVISORY',
          reason: 'Ambulance offload bay delays exceed 20 min threshold for Level 3 non-trauma cases.',
          expectedImpact: 'Divert ~6 non-critical incoming units over next 90 min',
          actionType: 'EMS_DIVERSION',
          impactPercentage: 10,
          status: 'PENDING',
        },
      ];
    }

    return [
      {
        id: 'rec-1',
        priority: 'CRITICAL',
        title: 'OPEN 4 ADDITIONAL BEDS',
        reason: 'Current acute bed occupancy is 89%. 4 reserve step-down observation beds can be staffed immediately.',
        expectedImpact: 'Reduce projected congestion by ~8%',
        actionType: 'OPEN_BEDS',
        impactPercentage: 8,
        status: 'PENDING',
      },
      {
        id: 'rec-2',
        priority: 'HIGH',
        title: 'REALLOCATE 2 NURSES',
        reason: 'Shift 2 nursing staff from Low-Acuity Outpatient Fast-Track to High-Dwell Triage queue.',
        expectedImpact: 'Reduce treatment queue pressure & lower triage wait',
        actionType: 'REALLOCATE_NURSES',
        impactPercentage: 6,
        status: 'PENDING',
      },
      {
        id: 'rec-3',
        priority: 'MEDIUM',
        title: 'PREPARE OVERFLOW AREA',
        reason: 'Waiting area currently holds 31/40 seats. Projected arrival pace will reach capacity in 40 min.',
        expectedImpact: 'Increase short-term waiting capacity by +15 seats',
        actionType: 'PREPARE_OVERFLOW',
        impactPercentage: 5,
        status: 'PENDING',
      },
    ];
  }

  simulateWhatIf(baseline: HospitalMetrics, params: WhatIfParameters): WhatIfSimulationResult {
    // Deterministic transparent operations formula
    // Baseline state:
    const baseCongestion = baseline.congestionRisk;
    const baseWait = baseline.averageWaitTime;
    const baseOccupancy = Math.round((baseline.bedsOccupied / baseline.bedsTotal) * 100);
    const baseStaffRatio = Number((baseline.patientsWaiting / Math.max(1, baseline.staffNurses)).toFixed(1));

    // Impact of additional beds: each bed reduces congestion by ~1.8% and wait by ~1.2 min
    const bedEffect = params.additionalBeds * 1.8;
    const bedWaitEffect = params.additionalBeds * 1.4;

    // Impact of additional nurses: each nurse relieves queue pressure by ~2.2% and wait by ~2.1 min
    const nurseEffect = params.additionalNurses * 2.2;
    const nurseWaitEffect = params.additionalNurses * 2.5;

    // Impact of additional doctors: each doctor enhances throughput by ~3.0% and wait by ~3.2 min
    const doctorEffect = params.additionalDoctors * 3.0;
    const doctorWaitEffect = params.additionalDoctors * 3.5;

    // Impact of arrival surge (+% arrival increases congestion and wait time)
    const arrivalEffect = (params.arrivalSurge / 100) * 28;
    const arrivalWaitEffect = (params.arrivalSurge / 100) * 35;

    // Impact of treatment capacity boost (+% capacity reduces congestion and wait time)
    const capacityEffect = (params.treatmentCapacity / 100) * 22;
    const capacityWaitEffect = (params.treatmentCapacity / 100) * 25;

    // Combined net simulation:
    const netCongestionDelta = Math.round(-bedEffect - nurseEffect - doctorEffect + arrivalEffect - capacityEffect);
    const netWaitDelta = Math.round(-bedWaitEffect - nurseWaitEffect - doctorWaitEffect + arrivalWaitEffect - capacityWaitEffect);

    const simulatedCongestion = Math.max(15, Math.min(99, baseCongestion + netCongestionDelta));
    const simulatedWait = Math.max(12, Math.min(180, baseWait + netWaitDelta));

    const totalSimulatedBeds = baseline.bedsTotal + params.additionalBeds;
    const simulatedOccupancy = Math.min(100, Math.max(20, Math.round(
      ((baseline.bedsOccupied + (params.arrivalSurge > 0 ? Math.round(params.arrivalSurge * 0.1) : 0)) / totalSimulatedBeds) * 100
    )));

    const simulatedNurses = baseline.staffNurses + params.additionalNurses;
    const simulatedStaffRatio = Number((Math.max(4, baseline.patientsWaiting + (params.arrivalSurge * 0.2)) / Math.max(1, simulatedNurses)).toFixed(1));

    let impactSummary = 'Scenario results indicate balanced capacity.';
    if (netCongestionDelta <= -10) {
      impactSummary = `Decisive operational stabilization: Projected congestion reduced by ${Math.abs(netCongestionDelta)}% with a ${Math.abs(netWaitDelta)} min wait reduction.`;
    } else if (netCongestionDelta < 0) {
      impactSummary = `Moderate queue relief: Projected congestion decreased by ${Math.abs(netCongestionDelta)}%.`;
    } else if (netCongestionDelta > 10) {
      impactSummary = `Critical bottleneck warning: Surge conditions outpace capacity by +${netCongestionDelta}% without staffing buffers.`;
    }

    return {
      baseline: {
        congestionRisk: baseCongestion,
        waitTime: baseWait,
        bedOccupancyRate: baseOccupancy,
        staffRatio: baseStaffRatio,
      },
      simulated: {
        congestionRisk: simulatedCongestion,
        waitTime: simulatedWait,
        bedOccupancyRate: simulatedOccupancy,
        staffRatio: simulatedStaffRatio,
      },
      deltas: {
        congestionDelta: netCongestionDelta,
        waitTimeDelta: netWaitDelta,
        bedOccupancyDelta: simulatedOccupancy - baseOccupancy,
      },
      impactSummary,
    };
  }
}

// Export singleton instance of predictionService (can be swapped in production)
export const predictionService: IPredictionService = new DeterministicPredictionEngine();
